### PR TITLE
export redux and selectors so it can be easily imported from chonky lib.

### PR DESCRIPTION
**Pull request by tuan43**
the new version is missing imports of core redux fns.

### CODE REVIEW

**Comment by tuan43** [comment]
@TimboKZ , this is related to issue #115

**Comment by tuan43** [comment]
can someone review and merge in this PR? would love to import the chonky redux states, selectors, etc.

**Comment by TimboKZ** [comment]
Hey Tuan, will review and merge in the next few days.

**Comment by tuan43** [comment]
@TimboKZ , any updates on this?

**Comment by tuan43** [comment]
@TimboKZ , happy holidays. Sorry, not trying to be a pain, but can this please get reviewed and merged in? 

Thanks,
Tuan

**Review by TimboKZ — APPROVED** [review]

**Comment by tuan43** [comment]
Thanks! How would I get a npm package with this change?

**Comment by TimboKZ** [comment]
Hi, I'm addressing some other issue at the moment, will release all the changes at the same time once I'm done (which will probably be in a few hours).

**Pull request merged**
